type = "checkout_ui_extension"
name = "test-banner"

extension_points = [
  'Checkout::Dynamic::Render'
]

# Read more on extension settings at https://shopify.dev/api/checkout-extensions/checkout/configuration
[settings]

  [[settings.fields]]
  key = "show_notification"
  type = "boolean"
  name = "Show notification"
  description = "Check to show notifications"

  [[settings.fields]]
  key = "sum_level_1"
  type = "number_integer"
  name = "Minimum purchase requirements"
  description = "Set minimum quantity for level 1"

  [[settings.fields]]
  key = "msg_level_1"
  type = "single_line_text_field"
  name = "Message about discount"
  description = "Set text for level 1 discount message. Use [[difference]] to display amount is missing to activate discount"

[[settings.fields]]
  key = "sum_level_2"
  type = "number_integer"
  name = "Minimum purchase requirements"
  description = "Set minimum quantity for level 2"

  [[settings.fields]]
  key = "msg_level_2"
  type = "single_line_text_field"
  name = "Message about discount"
  description = "Set text for level 2 discount message. Use [[difference]] to display amount is missing to activate discount"

